### PR TITLE
Add input buffer

### PR DESCRIPTION
**Pull request by danielmonterocr**
The newest version of Swig is needed to use the built in typemaps for buffers so the Dockerfile downloads and installs version 4.0.1.

- [x] C: use an input buffer instead of a file to update the value of the parameters
- [x] C: run covid19ibm.exe
- [x] C: valgrind covid19ibm.exe
- [x] Python: add utility functions to pass buffer from Python
- [x] Python: load params file and pass it to C program
- [x] Python: load household file and pass it to C program
- [ ] Python: load hospital file and pass it to C program
- [x] Python: pass all tests
- [x] Python: valgrind all tests

### CODE REVIEW

**Comment by danielmonterocr** [comment]
Maybe tomorrow with the release of Ubuntu 20.04 we can get rid of this.

**Comment by danielmonterocr** [comment]
@roberthinch @p-robot please review

**Comment by danielmonterocr** [comment]
@brynmathias can you give this one a final review?

**Comment by roberthinch** [comment]
Functionally added in other PRs

**Pull request closed without merging**
