### PR TITLE
Performance generalize

### PR DESCRIPTION
**Pull request by RossBoylan**
The current code in test_performance appears to use profiling tools in OS-X.
This change puts some guards around that.
I may eventually make changes to use other tools, but that's more involved.

I get about 152s when I run out of the box and 109 when I compile without -g and with -O3.
So I seem to be way over the script's time limit.  But I do not get the warning message.

I presume the test `[ $RUNTIME \> 40 ]` in the script is doing a lexicographic rather than numeric comparison.  I'll probably push a fix for that in the same branch.

Is 40 still an appropriate cutoff given the current state of the model?  My machine is reasonably new and fast.

### CODE REVIEW

**Comment by RossBoylan** [comment]
Ack!  I guess I should have picked my base branch for the pull request more carefully.  This is showing as a huge number of commits because of the weird history I ended up with when you switched master to a different development stream a few days ago (as far as I can tell).  Not sure if it matters.  But the only change intended is (currently) a single commit with changes to `test_peformance.sh`

**Comment by RossBoylan** [comment]
I created a much cleaner pull request, but apparently only for myself: https://github.com/RossBoylan/OpenABM-Covid19/pull/1#issue-434050582.  Still learning...

**Comment by roberthinch** [comment]
Yes, this was used very early on in the development when the model was first being built (on my rather old Mac hence OSX tools). At the time the time the population was 100k (and it would take 20-30s), however, this has increased to 1m, hence the slower time. So 300s is probably a better cutoff now to catch howlers. 

You'll need to check out the repo again fresh and then copy in your changes (there were some problems in the middle of the commit history in a PR last week which meant we needed to do a force push to remove them hence the problem with 250+ commits in your PR).

**Comment by RossBoylan** [comment]
I created a changeset with a completely different history, albeit the same branch name.
I got the latest `master` from here and then took 
https://github.com/p-robot/OpenABM-Covid19/tree/performance_generalize
from @p-robot.  Finally I increased the allowed test time to 300 s as suggested above.

*However* with the new code even that does not seem enough.  The test was running in ~ 110 s
for me earlier, but now takes 434 s. My test, as before, was run with code compiled with `O3`, specifically
https://github.com/RossBoylan/OpenABM-Covid19/tree/sf.

I do not know whether all this rewriting history and `push --force` will simply be tracked by this pull
request or not.  If tracking is by name, "performance_generalize" it should be fine, but if it's recording 
the hash, it won't...

```
(jarenv) ross@barley:/usr/local/jar/OpenABM-Covid19/performance$ ./test_performance.sh 
# Starting simulation
# Date: 03-07-2020 02:29:14
# Read command-line args
# Read input parameter file
# Read household demographics file
# Start model set-up
# param_id: 1
# rng_seed: 1
# param_line_number: 1
# hospital_on: 0
time,lockdown,lockdown_elderly,intervention_on,test_on_symptoms,app_on,total_infected,total_case,n_presymptom,n_asymptom,n_quarantine,n_tests,n_symptoms,n_hospital,n_critical,n_hospitalised_recovering,n_death,n_recovered,n_quarantine_infected,n_quarantine_recovered,n_quarantine_app_user,n_quarantine_app_user_infected,n_quarantine_app_user_recovered,n_quarantine_events,n_quarantine_events_app_user,n_quarantine_release_events,n_quarantine_release_events_app_user
1,0,0,1,0,0,5,0,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,5,0,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
# etc.  Here are a few of the longest lines
75,0,0,1,0,0,692351,12227,69385,147534,2038,1170,211569,5978,1024,39,4983,251839,2038,857,1028,1028,547,167,100,111,56
76,0,0,1,0,0,705803,12972,62404,142826,2097,1101,209586,6107,1085,46,5342,278407,2097,892,1051,1051,572,170,80,111,57
77,0,0,1,0,0,717482,13741,55948,137238,2166,1158,205610,6088,1120,50,5712,305716,2166,924,1099,1099,602,180,102,111,54
#....
200,0,0,1,0,0,790914,19040,0,0,0,0,0,0,0,0,9651,781263,0,0,0,0,0,0,0,0,0

# End_time:                      200
# Total population:              1000000
# Total edges in network:        1685283
# Total total interactions:      1256008333
# Total infected:                790914
# Total cases:                   19040
# Total cases   0-9 years:       0
# Total cases 10-19 years:       7
# Total cases 20-29 years:       61
# Total cases 30-39 years:       369
# Total cases 40-49 years:       1539
# Total cases 50-59 years:       2961
# Total cases 60-69 years:       4507
# Total cases 70-79 years:       5376
# Total cases   80+ years:       4220
# Total deaths:                  9651
# Total deaths   0-9 years:      0
# Total deaths 10-19 years:      0
# Total deaths 20-29 years:      2
# Total deaths 30-39 years:      22
# Total deaths 40-49 years:      85
# Total deaths 50-59 years:      434
# Total deaths 60-69 years:      1491
# Total deaths 70-79 years:      3246
# Total deaths   80+ years:      4371
# Total quarantined days:        52419
# Ending simulation, run time:   433.39s
execution time was 434 seconds

*********************************
** FAILURE - TOO SLOW
*********************************
```
gcc (Debian 8.3.0-6) 8.3.0
Python 3.7.3

**Comment by RossBoylan** [comment]
> Please rebase and increase the run time to 300 then we can merge.

I believe I've done both with the latest changes.  I'm not sure if there's some more sophisticate way I'm supposed to indicate that other than sending this message.

As noted in my earlier message, the test seems to have gotten a lot slower, and, at least on my machine, the test fails even with 300s permitted.  It's about 4x slower than it was, which is quite concerning if it's not from some expansion of the test suite.

**Pull request closed without merging**
