### PR TITLE
Allow updating lockdown multiplier parameters

### PR DESCRIPTION
**Pull request by srstevenson**
`lockdown_house_interaction_multiplier`, `lockdown_random_network_multiplier`, and `lockdown_work_network_multiplier` can now be updated whilst the model is running. This allows modelling evolving lockdown conditions.

### CODE REVIEW

**Comment by roberthinch** [comment]
Please can you make one change. Can you only call `set_model_param_lockdown_on` when lockdown_on = TRUE, alternatively at the top of `set_model_param_lockdown_on`  do nothing if it is currently FALSE and is being set to FALSE (latter is probably better as provides general protection). This is because there are few random variables drawn during the setting of lockdown on/off and we do not want to change their values if the change in parameters does nothing (if lockdown is on then there will be changes anyway).

**Comment by srstevenson** [comment]
Thanks Rob; in the latter case, is it a problem that `daily_fraction_work_used` and `relative_transmission_used` don't get updated using the new values of  `lockdown_work_network_multiplier` and `lockdown_house_interaction_multiplier`? This otherwise happens here:
https://github.com/BDI-pathogens/OpenABM-Covid19/blob/cd07222e7c76c36877b3a7d6afa230a0990eb176/src/params.c#L388-L392

**Comment by roberthinch** [comment]
This only happens when lockdown_on = TRUE so is not a problem.
However, there is a good point that if the elderly lockdown is on then it
won't pick up the new parameters.
So, i think you need in your new set functions to have: if( lockdown_on )
set_lockdown on else if( elderly_lockdown_on) set_elderly_lockdown on else
do nothing.
Note if the main lockdown is on then you don't need to call elderly
lockdown on separately.

**Comment by srstevenson** [comment]
Thanks for the pointers @roberthinch, I've implemented and pushed those.

**Pull request merged**
