### PR TITLE
Major update of baseline parameters

### PR DESCRIPTION
**Pull request by MichelleKendall**
This is the major update of the baseline parameters following the work of the team over the last couple of weeks.

### CODE REVIEW

**Comment by roberthinch** [comment]
A couple of questions: 

1. In the proposed parameters we have: `sd_time_hospitalised_recovery `> `mean_hospitalised_recovery`. Given that we are using a gamma distribution we will probably get some funky behaviour (i.e. mode = 0).

**Comment by MichelleKendall** [comment]
Thanks.
1. I checked and these values do come from a gamma distribution in the original. But I think if it's necessary for avoiding funky behaviour then we could reasonably change the sd to equal the mean?
2. These have not been addressed in the latest review. Happy for you to reduce them - do you have a reference or is it rule of thumb?

**Comment by roberthinch** [comment]
1. Yes sd=mean gives an exponential distribution which is fine. 
2. Rule of thumb I think they should be more like 0.5 and 0.1. It should not be difficult to back out from age-stratified data for ICU and deaths.

**Comment by MichelleKendall** [comment]
1. Excellent
2. Sure. Looking into it.

**Pull request merged**
