### PR TITLE
Update C arrays using Python lists

### PR DESCRIPTION
**Pull request by danielmonterocr**
How to use it:

```
➜  src (update-c-arrays-using-python-lists) ✗ python3.7
Python 3.7.7 (default, Mar 10 2020, 15:43:33)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import covid19
>>> params = covid19.parameters()
>>> set_array = covid19.doubleArray(covid19.N_AGE_TYPES)
>>> exec("for i in range(covid19.N_AGE_TYPES): set_array[i] = i")
>>> exec("for i in range(covid19.N_AGE_TYPES): print(set_array[i])")
0.0
1.0
2.0
>>> covid19.set_param_mean_random_interactions(params, set_array)
>>> get_array = covid19.doubleArray(covid19.N_AGE_TYPES)
>>> covid19.get_param_mean_random_interactions(params, get_array)
>>> exec("for i in range(covid19.N_AGE_TYPES): print(get_array[i])")
0.0
1.0
2.0
>>>
```

### CODE REVIEW

**Comment by brynmathias** [comment]
I would make sure we dont break the functionality of setting by index
Being able to update a single parameter is super useful
This will also then not break the tests.

We can then write some tests for setting by arrays and work out how we read the params in from the params file using these setting methods

**Comment by brynmathias** [comment]
This change requires a later version of swig?
If so can you add the install guide for that to the README as well please?

**Comment by danielmonterocr** [comment]
@brynmathias not this one, it works ok with our current version

**Comment by brynmathias** [comment]
I think the fail on this test is due to something wrong with the container, rather than an actual fail

**Comment by danielmonterocr** [comment]
Yes all tests pass locally

**Comment by danielmonterocr** [comment]
@roberthinch I removed those set functions and yes these functions will only work prior to model creation.

**Pull request merged**
